// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RpcMessage.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49baf2e5143a5e0, []int{0}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*String)(nil), "ProtoMessage.String")
}

func init() { proto.RegisterFile("RpcMessage.proto", fileDescriptor_a49baf2e5143a5e0) }

var fileDescriptor_a49baf2e5143a5e0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x2a, 0x48, 0xf6,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x09, 0x00,
	0x51, 0x50, 0x31, 0x25, 0x39, 0x2e, 0xb6, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0x74, 0x21, 0x11, 0x2e,
	0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0xc7, 0xa8,
	0x82, 0x8b, 0xc7, 0x23, 0x35, 0x27, 0x27, 0x3f, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x98, 0x8b, 0x15, 0xcc, 0x17, 0x12, 0xd1, 0x43, 0x36, 0x47, 0x0f, 0x62, 0x88, 0x14, 0x56, 0x51,
	0x90, 0x26, 0xe7, 0x9c, 0xfc, 0xe2, 0x54, 0x52, 0x34, 0x39, 0x49, 0x71, 0xf1, 0xe7, 0x17, 0xa5,
	0xeb, 0xe5, 0xe6, 0xe6, 0xeb, 0xe5, 0x42, 0x64, 0xa2, 0xd8, 0xa1, 0x8c, 0x24, 0x36, 0xb0, 0x57,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x23, 0xf1, 0xc4, 0xde, 0x00, 0x00, 0x00,
}
