// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServerMessage.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//服务器列表
type ServerListRequest struct {
	MsgID                MID      `protobuf:"varint,1,opt,name=msgID,proto3,enum=ProtoMessage.MID" json:"msgID,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerListRequest) Reset()         { *m = ServerListRequest{} }
func (m *ServerListRequest) String() string { return proto.CompactTextString(m) }
func (*ServerListRequest) ProtoMessage()    {}
func (*ServerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_741c7e7fb9e8b054, []int{0}
}

func (m *ServerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListRequest.Unmarshal(m, b)
}
func (m *ServerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListRequest.Marshal(b, m, deterministic)
}
func (m *ServerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListRequest.Merge(m, src)
}
func (m *ServerListRequest) XXX_Size() int {
	return xxx_messageInfo_ServerListRequest.Size(m)
}
func (m *ServerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListRequest proto.InternalMessageInfo

func (m *ServerListRequest) GetMsgID() MID {
	if m != nil {
		return m.MsgID
	}
	return MID_None
}

func (m *ServerListRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ServerListResponse struct {
	MsgID                MID           `protobuf:"varint,1,opt,name=msgID,proto3,enum=ProtoMessage.MID" json:"msgID,omitempty"`
	Server               []*ServerInfo `protobuf:"bytes,2,rep,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerListResponse) Reset()         { *m = ServerListResponse{} }
func (m *ServerListResponse) String() string { return proto.CompactTextString(m) }
func (*ServerListResponse) ProtoMessage()    {}
func (*ServerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_741c7e7fb9e8b054, []int{1}
}

func (m *ServerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListResponse.Unmarshal(m, b)
}
func (m *ServerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListResponse.Marshal(b, m, deterministic)
}
func (m *ServerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListResponse.Merge(m, src)
}
func (m *ServerListResponse) XXX_Size() int {
	return xxx_messageInfo_ServerListResponse.Size(m)
}
func (m *ServerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListResponse proto.InternalMessageInfo

func (m *ServerListResponse) GetMsgID() MID {
	if m != nil {
		return m.MsgID
	}
	return MID_None
}

func (m *ServerListResponse) GetServer() []*ServerInfo {
	if m != nil {
		return m.Server
	}
	return nil
}

// 服务器信息
type ServerInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BelongID             int32    `protobuf:"varint,2,opt,name=belongID,proto3" json:"belongID,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Content              string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Online               int32    `protobuf:"varint,11,opt,name=online,proto3" json:"online,omitempty"`
	MaxUserCount         int32    `protobuf:"varint,12,opt,name=maxUserCount,proto3" json:"maxUserCount,omitempty"`
	HttpPort             int32    `protobuf:"varint,13,opt,name=httpPort,proto3" json:"httpPort,omitempty"`
	OpenTime             string   `protobuf:"bytes,14,opt,name=openTime,proto3" json:"openTime,omitempty"`
	MaintainTime         string   `protobuf:"bytes,15,opt,name=maintainTime,proto3" json:"maintainTime,omitempty"`
	Name                 string   `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	Wwwip                string   `protobuf:"bytes,17,opt,name=wwwip,proto3" json:"wwwip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_741c7e7fb9e8b054, []int{2}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServerInfo) GetBelongID() int32 {
	if m != nil {
		return m.BelongID
	}
	return 0
}

func (m *ServerInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServerInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ServerInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ServerInfo) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *ServerInfo) GetMaxUserCount() int32 {
	if m != nil {
		return m.MaxUserCount
	}
	return 0
}

func (m *ServerInfo) GetHttpPort() int32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ServerInfo) GetOpenTime() string {
	if m != nil {
		return m.OpenTime
	}
	return ""
}

func (m *ServerInfo) GetMaintainTime() string {
	if m != nil {
		return m.MaintainTime
	}
	return ""
}

func (m *ServerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerInfo) GetWwwip() string {
	if m != nil {
		return m.Wwwip
	}
	return ""
}

// 注册更新服务器
type ServerRegisterUpdateRequest struct {
	MsgID                MID         `protobuf:"varint,1,opt,name=msgID,proto3,enum=ProtoMessage.MID" json:"msgID,omitempty"`
	ServerInfo           *ServerInfo `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerRegisterUpdateRequest) Reset()         { *m = ServerRegisterUpdateRequest{} }
func (m *ServerRegisterUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ServerRegisterUpdateRequest) ProtoMessage()    {}
func (*ServerRegisterUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_741c7e7fb9e8b054, []int{3}
}

func (m *ServerRegisterUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerRegisterUpdateRequest.Unmarshal(m, b)
}
func (m *ServerRegisterUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerRegisterUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ServerRegisterUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerRegisterUpdateRequest.Merge(m, src)
}
func (m *ServerRegisterUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ServerRegisterUpdateRequest.Size(m)
}
func (m *ServerRegisterUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerRegisterUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerRegisterUpdateRequest proto.InternalMessageInfo

func (m *ServerRegisterUpdateRequest) GetMsgID() MID {
	if m != nil {
		return m.MsgID
	}
	return MID_None
}

func (m *ServerRegisterUpdateRequest) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerListRequest)(nil), "ProtoMessage.ServerListRequest")
	proto.RegisterType((*ServerListResponse)(nil), "ProtoMessage.ServerListResponse")
	proto.RegisterType((*ServerInfo)(nil), "ProtoMessage.ServerInfo")
	proto.RegisterType((*ServerRegisterUpdateRequest)(nil), "ProtoMessage.ServerRegisterUpdateRequest")
}

func init() { proto.RegisterFile("ServerMessage.proto", fileDescriptor_741c7e7fb9e8b054) }

var fileDescriptor_741c7e7fb9e8b054 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3d, 0x0f, 0xd3, 0x30,
	0x10, 0x55, 0xd2, 0x26, 0x2d, 0xd7, 0xd2, 0x0f, 0x83, 0x90, 0x55, 0x96, 0x28, 0x0b, 0x99, 0x22,
	0x54, 0x16, 0x66, 0xe8, 0x12, 0x89, 0x4a, 0x55, 0xa0, 0x0b, 0x5b, 0x4a, 0x8f, 0x60, 0xa9, 0xb1,
	0x8d, 0xed, 0xb6, 0xb0, 0xf1, 0xc3, 0x19, 0x90, 0xed, 0x34, 0x6d, 0x16, 0x04, 0x53, 0xee, 0xbd,
	0x77, 0x7e, 0xe7, 0x97, 0x33, 0x3c, 0xfb, 0x88, 0xea, 0x82, 0x6a, 0x8b, 0x5a, 0x57, 0x35, 0xe6,
	0x52, 0x09, 0x23, 0xc8, 0x74, 0x67, 0x3f, 0x2d, 0xb7, 0x5a, 0x6c, 0x8b, 0x4d, 0x4f, 0x4f, 0x77,
	0xb0, 0xf4, 0xc7, 0x3e, 0x30, 0x6d, 0x4a, 0xfc, 0x7e, 0x46, 0x6d, 0xc8, 0x2b, 0x88, 0x1a, 0x5d,
	0x17, 0x1b, 0x1a, 0x24, 0x41, 0x36, 0x5b, 0x2f, 0xf3, 0x47, 0x93, 0x7c, 0x5b, 0x6c, 0x4a, 0xaf,
	0x13, 0x02, 0x43, 0xf3, 0x53, 0x22, 0x0d, 0x93, 0x20, 0x8b, 0x4a, 0x57, 0xa7, 0x02, 0xc8, 0xa3,
	0xa3, 0x96, 0x82, 0x6b, 0xfc, 0x77, 0xcb, 0xd7, 0x10, 0x6b, 0x77, 0x9c, 0x86, 0xc9, 0x20, 0x9b,
	0xac, 0x69, 0xbf, 0xd3, 0x5b, 0x17, 0xfc, 0xab, 0x28, 0xdb, 0xbe, 0xf4, 0x77, 0x08, 0x70, 0xa7,
	0xc9, 0x0c, 0x42, 0x76, 0x74, 0x63, 0xa2, 0x32, 0x64, 0x47, 0xb2, 0x82, 0xf1, 0x01, 0x4f, 0x82,
	0xdb, 0xe1, 0xfe, 0x9e, 0x1d, 0x76, 0xbd, 0x92, 0x0e, 0x92, 0x20, 0x7b, 0x52, 0x86, 0x4c, 0x76,
	0x79, 0x86, 0xf7, 0x3c, 0x96, 0x93, 0x42, 0x19, 0x1a, 0x79, 0xce, 0xd6, 0xe4, 0x39, 0x44, 0xda,
	0x54, 0x06, 0x69, 0xec, 0x48, 0x0f, 0x08, 0x85, 0xd1, 0x05, 0x95, 0x66, 0x82, 0xd3, 0x91, 0xb3,
	0xbc, 0x41, 0xab, 0x7c, 0x11, 0xdc, 0x20, 0x37, 0x74, 0xec, 0x95, 0x16, 0x92, 0x17, 0x10, 0x0b,
	0x7e, 0x62, 0x1c, 0xe9, 0xc4, 0x59, 0xb5, 0x88, 0xa4, 0x30, 0x6d, 0xaa, 0x1f, 0x7b, 0x8d, 0xea,
	0xbd, 0x38, 0x73, 0x43, 0xa7, 0x4e, 0xed, 0x71, 0x36, 0xd9, 0x37, 0x63, 0xe4, 0xce, 0xde, 0xee,
	0xa9, 0x4f, 0x76, 0xc3, 0x56, 0x13, 0x12, 0xf9, 0x27, 0xd6, 0x20, 0x9d, 0xb9, 0x91, 0x1d, 0xf6,
	0xde, 0x8c, 0x9b, 0x8a, 0x79, 0x7d, 0xee, 0xf4, 0x1e, 0x67, 0x53, 0xf3, 0xaa, 0x41, 0xba, 0x70,
	0x9a, 0xab, 0x6d, 0xea, 0xeb, 0xf5, 0xca, 0x24, 0x5d, 0x3a, 0xd2, 0x83, 0xf4, 0x57, 0x00, 0x2f,
	0xfd, 0xef, 0x2f, 0xb1, 0x66, 0xda, 0xa0, 0xda, 0xcb, 0x63, 0x65, 0xf0, 0xbf, 0x1f, 0xd3, 0x5b,
	0x00, 0xdd, 0xad, 0xd1, 0xad, 0xea, 0x6f, 0xdb, 0x7f, 0xe8, 0x7d, 0xb7, 0x82, 0xb9, 0x50, 0x75,
	0xde, 0x34, 0x22, 0x6f, 0x7c, 0xe7, 0xe7, 0x51, 0x5b, 0x1c, 0x62, 0xf7, 0xce, 0xdf, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xe6, 0x3a, 0x51, 0x1e, 0x03, 0x00, 0x00,
}
